### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-AlbaGomezPerez#1]
Hi @AlbaGomezPerez  !!!

Here you have some tips to improve the exercise:

- [ ] Fix the language and the meta title of the page
- [ ] Be extra careful with syntax, it looks like you have errors when closing the header element
- [ ] Should the `.menu` element be a non-semantics `div` or a rich semantic `nav` (commonly used for our main navigation)
- [ ] We should use lists (ul/li) for our navigation menu. A `UL` tag without her LI items is not a list.
- [ ] We need a nav and an h1 tags
- [ ] Menu items should be clickable
- [ ] Humanize text in `alt` attributes, a sentence without the dash `-` may do the trick ;).
- [ ] Move the font CSS link before your main CSS
- [ ] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color
- [ ] The main section should fit 100% of the browser's height
- [ ] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [ ] Avoid uppercase/capital on HTML texts, and `BR` tags,  we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [ ] Finish the main title styles: words should jump, and the font-family should be "Rubik."
- [ ] Fix color of links and main title size.
- [ ] Indent and avoid extra white spaces to improve readability and avoid bugs
- [ ] Write your classes in English!
- [ ] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed, try to finish the styles.
Start with the header and go step by step:

- add structural styles: center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margins, padding...
- add cosmetic styles: color, background color...

Then repeat the same with the main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by AlbaGomezPerez** [comment]
- [x] Fix the language a3782eecc54018e65f4688ae5e065079596d0baf
- [x] Meta title of the page ab34c2680b52d8abc94c448573d615cdea0fe1ed
- [x] Be extra careful with syntax, it looks like you have errors when closing the header element
- [x] Should the `.menu` element be a non-semantics `div` or a rich semantic `nav` (commonly used for our main navigation) 8f513eac80241f303fccbe1008528f201f6c34bb
- [x] We should use lists (ul/li) for our navigation menu. A `UL` tag without her LI items is not a list. 50a57a6a0a2a4585b7113e05aa6fb94e2ceedd8e
- [x] We need a nav and an h1 tags 56a92180aeedafaff81f6e512befc6bab8ea149e
- [x] Menu items should be clickable d779899a5d52d079325df592146a4600929f669b
- [x] Humanize text in `alt` attributes, a sentence without the dash `-` may do the trick ;). 969e993a71679707916dbe326a45b07e671ddf8a
- [x] Move the font CSS link before your main CSS d1cb5643ba251b3c5717e0c909ab853cb9fac0b7
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color 8236ad12236f1875e1cbf8eb71df1f75f7edbc8e
- [x] The main section should fit 100% of the browser's height e2c1b418beda2ed8170a1c603741c8fb318bc1d8
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;) d3101e89f5ead58a3735e8c668cf2624a7cea458
- [x] Avoid uppercase/capital on HTML texts, and `BR` tags,  we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles 56a92180aeedafaff81f6e512befc6bab8ea149e  99aa50ac58315ce7b2f74abf3797dca50178dc28
- [x] Finish the main title styles: words should jump, and the font-family should be "Rubik." 8236ad12236f1875e1cbf8eb71df1f75f7edbc8e
- [x] Fix color of links and main title size.
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs f40846cdbb1b8417a26fdcbef9a11adbd97d1501
- [x] Write your classes in English! 2e78e4293c2204634e5ce3e91f02a01d5880660a
- [x] Organize your files in folders, you have a guide to help you with that here -->  0034b767196f70b496c23e44e8ed0ae95e09fc49

**Comment by AlbaGomezPerez** [comment]
Hi Carlos! 
I've some problems with the nav on the tablet format. My <li> tags don't appear inside their <ul>
I've created a new branch "third"
![Captura de pantalla 2019-07-07 a las 23 45 30](https://user-images.githubusercontent.com/52216730/60774270-314b1c00-a112-11e9-97db-bfd0cb9d0c92.png)
![Captura de pantalla 2019-07-07 a las 23 45 02](https://user-images.githubusercontent.com/52216730/60774271-314b1c00-a112-11e9-8957-b2fab42a8731.png)

**Comment by oneeyedman** [comment]
Hi, @AlbaGomezPerez. You can merge your branch with master and that's it. Well done!
